AST dump for ChapelContext after pass denormalize.
Module use list: Errors OwnedObject 

{
  function chpl__init_ChapelContext[468612](const in arg _ln[9365673]:int(64)[10], in arg _fn[9365675]:int(32)[66]) : void[4] "fast on" "insert line file info" "local fn" "module init" "resolved"
  {
    if chpl__init_ChapelContext_p[9309591]
    {
      goto _exit_chpl__init_ChapelContext[9309628] _exit_chpl__init_ChapelContext[9309628]
    }
    ref refIndentLevel[9309614]:int(32)[66] "temp"
    (9309612 call printModuleInit[386886] c"%*s\n" c"ChapelContext" 13 _ln[9365673] _fn[9365675])
    (9309618 'move' refIndentLevel[9309614](9309617 'addr of' moduleInitLevel[386877]))
    (9309621 '+=' refIndentLevel[9309614] 1)
    (9309597 'move' chpl__init_ChapelContext_p[9309591] 1)
    {
      (9305670 call chpl__init_Errors[468309] _ln[9365673] _fn[9365675])
      (9305672 call chpl__init_OwnedObject[468375] _ln[9365673] _fn[9365675])
    }
    (9309624 '-=' refIndentLevel[9309614] 1)
    label _exit_chpl__init_ChapelContext[9309628]
    (631826 return _void[46])
  }
  function chpl__verifyTypeContext[1799134](const  ref arg x[1799136]:endCountDiagsManager[68924]) : void[4] "fast on" "instantiated generic" "invisible fn" "local fn" "resolved" "fn synchronization free" "no return value for void"
  {
    (1799224 return _void[46])
  }
}